paypal:
  login: "user"
  url: "http://some-url.org/"

logging:
  level:
    sql: trace

spring:
  profiles:
    active:
      - dev

  jooq:
    sql-dialect: org.hibernate.dialect.PostgreSQLDialect

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  thymeleaf:
    prefix: classpath:/templates/
    suffix: ".html"
